/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Attack started at: 2024-07-24 21:21
Namespace(llm_name='Trelis/Meta-Llama-3-8B-Instruct-function-calling', max_gpu_memory={'0': '44GB', '1': '44GB', '2': '44GB', '3': '44GB', '4': '44GB'}, eval_device='cuda:7', max_new_tokens=512, scheduler_log_mode='console', agent_log_mode='console', llm_kernel_log_mode='console', use_backend=None, workflow_mode='automatic', attacker_tools_path='data/attacker_cases_dh.jsonl', tasks_path='data/agent_tasks/example/currencyexchange_agent_tasks.txt', agent_path='example/currencyexchange_agent', observation_prompt_injection=True, plan_attack=False, action_attack=False, direct_prompt_injection=False, attack_type='escape_characters', cot_backdoor=False)
Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]Downloading shards:  25%|██▌       | 1/4 [00:06<00:19,  6.41s/it]Downloading shards:  50%|█████     | 2/4 [00:11<00:11,  5.71s/it]Downloading shards:  50%|█████     | 2/4 [00:18<00:18,  9.19s/it]
Traceback (most recent call last):
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 162, in <module>
    main()
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 75, in main
    llm = llms.LLMKernel(
          ^^^^^^^^^^^^^^^
  File "/common/users/hz624/AgentAttackBench/aios/llm_core/llms.py", line 48, in __init__
    self.model = HfNativeLLM(
                 ^^^^^^^^^^^^
  File "/common/users/hz624/AgentAttackBench/aios/llm_core/llm_classes/base_llm.py", line 33, in __init__
    self.load_llm_and_tokenizer()
  File "/common/users/hz624/AgentAttackBench/aios/llm_core/llm_classes/hf_native_llm.py", line 24, in load_llm_and_tokenizer
    self.model = MODEL_CLASS[self.model_type].from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3593, in from_pretrained
    resolved_archive_file, sharded_metadata = get_checkpoint_shard_files(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/transformers/utils/hub.py", line 1079, in get_checkpoint_shard_files
    cached_filename = cached_file(
                      ^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/transformers/utils/hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1350, in _hf_hub_download_to_cache_dir
    _create_symlink(blob_path, pointer_path, new_blob=False)
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 915, in _create_symlink
    os.symlink(src_rel_or_abs, abs_dst)
FileExistsError: [Errno 17] File exists: '../../blobs/9d8284414296ae46645a3ecd3fa29d0f5c56e18994121c892adfda26a7409df3' -> '/filer/tmp1/hz624/.cache/huggingface/hub/models--Trelis--Meta-Llama-3-8B-Instruct-function-calling/snapshots/6c1843a461c3d6516b21d63c50470919310a65d8/model-00003-of-00004.safetensors'
