Attack started at: 2024-08-02 02:23
Namespace(llm_name='llama3.1:8b', max_gpu_memory=None, eval_device='cuda:7', max_new_tokens=1024, scheduler_log_mode='console', agent_log_mode='console', llm_kernel_log_mode='console', use_backend='ollama', workflow_mode='automatic', attacker_tools_path='data/all_attack_tools_non_aggressive.jsonl.jsonl', tasks_path='data/agent_task.jsonl', tools_info_path='data/all_normal_tools.jsonl', observation_prompt_injection=False, plan_attack=False, action_attack=False, direct_prompt_injection=True, attack_type='naive', cot_backdoor=False, result_file='logs/result_file.log')
[ðŸ¤–llama3.1:8b] AIOS LLM successfully loaded.

Traceback (most recent call last):
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 207, in <module>
    main()
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 114, in main
    attacker_tools_all = pd.read_json(args.attacker_tools_path, lines=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 815, in read_json
    return json_reader.read()
           ^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1023, in read
    obj = self._get_object_parser(self._combine_lines(data_lines))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1051, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1187, in parse
    self._parse()
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1403, in _parse
    ujson_loads(json, precise_float=self.precise_float), dtype=None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected object or value
