Attack started at: 2024-09-30 23:50
Namespace(llm_name='/', max_gpu_memory=None, eval_device=None, max_new_tokens=256, scheduler_log_mode='console', agent_log_mode='console', llm_kernel_log_mode='console', use_backend='vllm', workflow_mode='automatic', attacker_tools_path='data/all_attack_tools_non_aggressive.jsonl', tasks_path='data/agent_task.jsonl', tools_info_path='data/all_normal_tools.jsonl', observation_prompt_injection=False, plan_attack=False, action_attack=False, direct_prompt_injection=True, jailbreak=False, attack_type='combined_attack', defense_type=None, cot_backdoor=False, cot_clean=False, target='ResearcherProfileManager', trigger='in light of extant literature', memory_attack=False, clean=False, result_file='logs/result_file.log', database='memory_db/direct_prompt_injection/combined_attack_gpt-4o-mini', task_num=1, write_db=False, read_db=False)
Traceback (most recent call last):
  File "/common/home/jh2164/AgentAttackBench/main_attacker.py", line 296, in <module>
    main()
  File "/common/home/jh2164/AgentAttackBench/main_attacker.py", line 141, in main
    llm = llms.LLMKernel(
          ^^^^^^^^^^^^^^^
  File "/common/home/jh2164/AgentAttackBench/aios/llm_core/llms.py", line 40, in __init__
    self.model = vLLM(
                 ^^^^^
  File "/common/home/jh2164/AgentAttackBench/aios/llm_core/llm_classes/vllm.py", line 23, in __init__
    super().__init__(llm_name,
  File "/common/home/jh2164/AgentAttackBench/aios/llm_core/llm_classes/base_llm.py", line 30, in __init__
    self.load_llm_and_tokenizer()
  File "/common/home/jh2164/AgentAttackBench/aios/llm_core/llm_classes/vllm.py", line 31, in load_llm_and_tokenizer
    self.available_gpus = list(self.max_gpu_memory.keys())
                               ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keys'
